### ISSUE TITLE
check standard guards

### ISSUE THREAD

**Issue by stephenmathieson** [clibs/strndup#1]
we should check for things like `HAVE_STRDUP` and `HAVE_STRNDUP` to attempt to prevent compilation errors.

**Comment by jwerle** [comment]
+1 - I often compile feature checks to generate these macro constants as I'm sure others do as well

**Comment by stephenmathieson** [comment]
for large portable projects, it's a pretty common thing to do

**Comment by jwerle** [comment]
Yeah. I'm putting guards in both my `.h` and `.c` files for the `asprintf` implementation [here](https://github.com/littlstar/asprintf.c/blob/master/asprintf.h#L8) and [here](https://github.com/littlstar/asprintf.c/blob/master/asprintf.c#L8)

**Comment by stephenmathieson** [comment]
oh nice!  i didn't know you put that together.

btw, you should probably define `HAVE_ASPRINTF` then, right ;)

**Comment by jwerle** [comment]
WOMP - you're right hahah

**Comment by willemt** [comment]
good call re:  #ifndef HAVE_STRNDUP

Have made changes

**Comment by stephenmathieson** [comment]
cool thanks
