### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by maandree** [clibs/strndup#5]
`strndup(3P)` is a standard libc function. You should document why anyone would use this library rather than a feature-test macro that enables `strndup`.

Also, `strndup` is not a safe version of `strdup`. None of the `*n*` functions are safe version, and this assumption can be harmful.

**Comment by jwerle** [comment]
Hi @maandree,
We'd happily accept a PR for documentation.
A simple search for [undefined symbols _strndup](https://www.google.com/search?q=undefined+symbols+_strndup&oq=undefined+symbols+_strndup) should yield some sort of insight into "why" this implementation was created.

I believe most of us in this community are aware of the implications of using `strndup()`. Thanks for the note. However, it could be valuable to note an alternative with the usage of `memcpy()`, `malloc()`, etc.
We'd happily review a PR for a better implementation without the need for `strncpy()`.

**Comment by maandree** [comment]
"undefined symbols _strndup", that sounds like the libc does

```
#if THE_CONDITION
char* strndup(const char*, size_t);
#else
# define strndup _strndup
#endif
```

to refuse successful compile on insufficient feature-test macros.

Any in case, if a libc does not implement `strndup`, you should
not do anything about it elsewhere. Bring the libc up to date instead.
